#!/usr/bin/env bash

options=(
    style=round
    width=6.0
    hidpi=on
    # Kanagawa: crystalBlue active, sumiInk4 inactive
    active_color=0xff7e9cd8
    inactive_color=0xff54546d
)

borders "${options[@]}"
